Answer associated stuff
WastedLifetime/SurfingPenguin pull request #12
Opened 2018-05-04 03:35 UTC by zfrank7777

Create models, db operations, and APIs for answer to surveys.

2018-07-06 05:03 UTC, zfrank7777 commented
Unit tests had been added. Please review this PR again.

2018-07-06 16:56 UTC, amjltc295 requested changes
Good job. Just some minor problems to fix.
Note that the commit message `stash` and `stashed` should be revised.

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/API/Survey.py
> +@api.route(f'/create_survey')
Please remove the f here and the following ones

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/db_interface/SurveyFunctions.py
> +def new_answerlist(data):
It would be great if there are some comments about this function and the structure of data.

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/extensions/__init__.py
> -
This violates the Flake8 check, and so does surfing_penguin/routes.py:16:1

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/models.py
> +    where an Answer is a answer to only a question.
Typo a->an

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/routes.py
> +api_prefix = "/api/"+ver
Is there a reason for using the variable `ver` here?

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/routes.py
> +                      url_prefix=api_prefix)
The API's version below seems not using the `__version__`.

2018-07-06 16:56 UTC, amjltc295 commented on src/surfing_penguin/routes.py
> +from src.surfing_penguin.API import User, Survey
Flake8

2018-07-07 06:28 UTC, amjltc295 approved these changes
lgtm

2018-07-07 06:30 UTC, merged